### ISSUE TITLE
Passphrase shows in 'ps' listing

### ISSUE THREAD

**Issue by jblaine** [drduh/pwd.sh#10]
You're passing the gpg passphrase as an argument to gpg, which means it will show in any 'ps' listing while the gpg command is running.

% while :; do ps -ef | grep decrypt | grep -v grep; done
...
jblaine  27709 27704  0 13:24 pts/0    00:00:00               /usr/bin/gpg --decrypt --armor --batch --command-fd 0 --passphrase MyPasswordWasHere pwd.sh.safe

**Comment by drduh** [comment]
Hi,

I could not reproduce the ps output on OS X, but did see the argument with an OpenBSM audit. Can you try my fix in https://github.com/drduh/pwd.sh/commit/ec371cbeb71ad941929d6b41142dfba18eaa34a1?
