### ISSUE TITLE
Don't show created password

### ISSUE THREAD

**Issue by Zeriuno** [drduh/pwd.sh#17]
I think there is actually no need for pwd.sh to show a password just created: it would be safer to do so only if specified and to simply store it otherwise, without sending it to output.

**Comment by drduh** [comment]
The way I use the script is as follows. When a new password is needed, I use default options to generate a random character string I won't remember. I copy the password to clipboard with mouse selection and paste it in a browser window, for example. If the password isn't displayed, I would immediately have to unlock the safe a second time to access it. Can you recommend a better workflow? I would prefer not to add additional y/n prompts.

**Comment by cwoac** [comment]
Perhaps a modified form of #15 (which I am looking at PRing)  on top of #16 that also allows generating passwords, so if you specifiy something like `pwd.sh -w -u newsite` then it will generate the password and chuck (just) it to stdout. This way you can still use your workflow, or you could pipe the output to `/dev/null` (for zeriuno) or to something like pbcopy (for clipboard support)

**Comment by Zeriuno** [comment]
I might be completely wrong, but I think that mouse selection and manual copying is less efficient and safe than an automated solution. You, @drduh, don't need to remember the password? Great, then you don't even need to see it. @cwoac's idea might be the good one, only, in my opinion, it would have to be the other way round: no password shown, by default, unless it is asked (it might be `-s` for `show`).

**Comment by drduh** [comment]
@cwoac & @Zeriuno - great points. Would you be satisfied with the following compromise? If a password is generated interactively, it is displayed as is the case now. An additional mode of operation can be added to generate passwords with command line arguments, in which case the password is not displayed by default, but can be with an additional flag.

**Comment by Zeriuno** [comment]
Sounds fair to me, @drduh, as long as the cli arguments offer the same
possibilities of the interactive mode!

**Comment by drduh** [comment]
Now I have added some command line arguments which grant the ability to create passwords of desired length and not display them. This is documented in the README and I hope you will find this solution satisfactory.

**Comment by Zeriuno** [comment]
This is great! Thank you @drduh for listening to my advice :)
