### ISSUE TITLE
Security: unprotected unlocked vault?

### ISSUE THREAD

**Issue by jjshoe** [drduh/pwd.sh#19]
https://github.com/drduh/pwd.sh/blob/master/pwd.sh#L121

decrypt the safe
remove the username
add the new entry
remove any blank lines
encrypt the vault
copy it over the old vault

You've left the vault, with a known name, decrypted, with permissions that match umask. Danger, Danger Will Robinson.

**Comment by drduh** [comment]
Sorry, I don't follow. Unencrypted data is never written to disk in this script, rather it's passed in through a pipe. Could you clarify when/how you're seeing an unprotected vault?

**Comment by drduh** [comment]
Please open a detailed issue if there's a problem.
