### ISSUE TITLE
Add context for password

### ISSUE THREAD

**Issue by superfunkminister** [drduh/pwd.sh#20]
I have a lot of accounts with the same username, some context like "Twitter" or "Github" for each would help quickly look up a password and differentiate between them in a list.

**Comment by Heart1010** [comment]
+1

**Comment by massimob** [comment]
+1

**Comment by drduh** [comment]
Why not simply concatenate the service name and username when creating a password? Personally, I just remember which username applies to which site. I like to think of this as an additional security measure if the password database is compromised, although I concede this comes at the cost of convenience.

**Comment by bndw** [comment]
I've been using the concatenation method and it works quite well:

```
Read, write, or delete password? (r/w/d, default: r) w

  Username: github/bndw
```

**Comment by CrisBRM** [comment]
@bndw It's certainly not as elegant.

**Comment by drduh** [comment]
In the interest of keeping the code short, I instead recommend coming up with your own scheme for storing the same username for multiple sites, or multiple usernames for one site. For example, you could use `user1@github`, `user2@github` or `user1@gmail`, `user1@yahoo`, et cetera. I will update the README to suggest writing and reading passwords in this way.
