### ISSUE TITLE
Gist backup

### ISSUE THREAD

**Issue by davidbarton** [drduh/pwd.sh#26]
What do you think about optional gist backups? You can put pwd safe to a new secret gist repository and attempt to pull/push on read/write. On conflict you just output it and let user resolve manually.

And how do you feel about https://github.com/caodonnell/passman.sh fork?

**Comment by drduh** [comment]
That sounds like a cool idea and should only require a few new functions to accomplish. If you want to implement it though, please go ahead and fork, as I'm pretty happy copy/pasting the safe manually (Gmail drafts are my preferred medium). Let me know if you need any help.

That fork is very cool. I will definitely mention it now.
