### ISSUE TITLE
command adds a 'mDoneB' at the end of the copied password 

### ISSUE THREAD

**Issue by kairos0ne** [drduh/pwd.sh#27]
Hi I've been experiencing a strange issue as I get 'mDoneB' these included at the end of the copied password when using:

./pwd.sh r github | cut -f1 -d ' ' | tr -d '\n' | pbcopy

I tried a fresh copy and it worked for the first time but as soon as I wrote over the password. The copy command stops working. 

Please do help me if you know any reason for why this would happen. 

Thanks.

**Comment by drduh** [comment]
Thanks for the report and sorry about that - apparently I had poorly tested the line on Mac OS. Can you try this instead?

    /pwd.sh r github | cut -f 1 -d ' ' | awk 'NR==3{print $1}' | pbcopy

**Comment by kairos0ne** [comment]
Thanks a ton, that works perfectly.
