### ISSUE TITLE
CAST5 as default cipher algorithm.

### ISSUE THREAD

**Issue by debiangirl** [drduh/pwd.sh#29]
Its possible to change the default cipher method to AES256, I used to save my passwords in a file encrypted with AES256. Its possible to add this to the script? Or CAST5 its just fine and secure?
Thanks in advance.
... http://crypto.stackexchange.com/questions/24045/is-cast5-still-a-secure-algorithm-to-use

**Comment by drduh** [comment]
I am not qualified to comment about the quality of CAST5 (it's probably fine, if it's the default), but personally set AES256 in my GnuPG configuration file (`~/.gnupg/gpg.conf`) like so: https://github.com/drduh/config/blob/master/gpg.conf#L9
