### ISSUE TITLE
pwd.sh.safe can be edited and corrupted

### ISSUE THREAD

**Issue by neil-rutherford** [drduh/pwd.sh#35]
If someone can edit the PGP message in the file, then they can mess with the decryption. I'm envisioning a ransomware type attack where a bad actor gains access, changes a few random characters in the .safe file, and makes the program unable to decrypt the passwords. Kind of like, "I can't see your passwords, but neither can you until you pay me!" Big problem if the keys to someone's entire digital life are stored in that file.

Is there some way to make the .safe file read-only except when pwd.sh is using it?

**Comment by mblumtritt** [comment]
The only thing what helps against ransomware is external backup and backup of the backups which are stored externally…

The described problem is not a problem of pwd.sh but of your data integrity. You should generally think about this and organize a working backup plan for your data.

**Comment by neil-rutherford** [comment]
Thanks for your input. I agree with you that backups are a good way to protect your data integrity.

However, on the off-chance someone failed to back up their passwords, a "game over" error could result from a bash one-liner: `cd ~/pwd.sh && echo ":/" > pwd.sh.safe`. I view this as a weakness in pwd.sh because such a crucial component can be corrupted so easily. My suggestion would be to change permissions using chmod, like so:

{START}
chmod +r+w pwd.sh.safe     #Adds read and write permissions so pwd.sh can do its thing
{OLD PWD.SH SCRIPT}
chmod -r-w pwd.sh.safe     #Removes read and write permissions to thwart shenanigans
{EXIT}

I've attached some logs from my terminal that show how changing permissions can hopefully make your program safer. Hope that helps!
[demo.txt](https://github.com/drduh/pwd.sh/files/3878346/demo.txt)

**Comment by drduh** [comment]
Write protection and versioning/backups sound like great ideas. I'm already working on new features and will include your suggestions in an upcoming release. Thanks for sharing!

**Comment by drduh** [comment]
Please try the new beta release and let me know what you think:
https://github.com/drduh/pwd.sh/releases/tag/2.0b
