### ISSUE TITLE
add "-sel clip" to xclip?

### ISSUE THREAD

**Issue by danielemiliogarcia** [drduh/pwd.sh#38]
is there any security risk adding "-sel clip" to xcopy?
the password was not getting copied to my clipboard in ubuntu linux, and that did the trick, i left a PR

**Comment by drduh** [comment]
I don't think so. AFAIK there's at least two clipboards on X and it's just a matter of using the primary or secondary one. Do you get the same paste behavior with Shift-Insert and middle-mouse button?
