### ISSUE TITLE
Bash font color changes aren't reseted

### ISSUE THREAD

**Issue by Feliix42** [drduh/pwd.sh#9]
Hello,
first of all, I'd like to let you know that I love the idea you came up with in this repository! Keep on developing it!

After I cloned the repo and started using the script, I intentionally produced an error. I like the red error message, but the font color is never reseted, so all the console output was red, until the 'success' message came. Here is the screenshot:
![color-bug](https://cloud.githubusercontent.com/assets/9332912/8502456/61e1bc7e-21b0-11e5-9913-bdaba19016f9.png)

I'm using `Mac OS X 10.10.4` on a mid-2013 Air. I am not using any other scripts that could possibly override any color settings in the bash.

**Comment by drduh** [comment]
Can you try this fix I just committed?

https://github.com/drduh/pwd.sh/commit/e3a3c78464a866fb9aa36155686dbd5acf57edc1

**Comment by Feliix42** [comment]
It works fine now! Thanks!
